name: Generate xml sitemap

on:
  push:
    branches: [ main ] # Change to master if your default branch is master

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required to accurately get file modification times

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://github.io

    - name: Commit and push sitemap
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git commit -m "Automated sitemap update" || exit 0
        git push
